# The world address to index
world_address = "0x33ae3bb60e5932deac28e716d247823184596a20f6a448e198e104daa8e5a2a"

# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/sepolia"


# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
# historical = ["full_starter_react-TrophyProgression"]
