[package]
name = "hexcore_logic"
cairo-version = "2.10.1"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
# No dojo dependency for pure core logic

[dev-dependencies]
cairo_test = "2.10.1"